version: "3.8"
services:
  bot:
    build:
      context: .
    env_file:
      - .env
    
#   qdrant:
#     image: qdrant/qdrant:latest
#     container_name: qdrant
#     ports:
#       - "6333:6333"
#     volumes:
#       - qdrant_storage:/qdrant/storage
#     restart: unless-stopped

# volumes:
#   qdrant_storage: